### ISSUE TITLE
White theme

### ISSUE THREAD

**Issue by Madis0** [NiklasGollenstede/re-style#11]
I prefer white backgrounds on my browser, so would be nice if reStyle had an option to toggle the theme.

**Comment by NiklasGollenstede** [comment]
reStyle can theme itself. All the colors in the main UI are specified in [this file](https://github.com/NiklasGollenstede/web-ext-utils/blob/master/options/editor/dark.css).

If you create a copy of that as a user style, wrap it in a `@document` block and replace all the color, you should be able to build a light theme rather quickly.

```css
@-moz-document
	regexp("moz-extension://[\w-]+/reStyle(?!#panel).*")
{
	/* modified theme */
}
```

If the result looks decent I am happy to include it in the extension itself (and would then also change the panel and a bit of other stuff accordingly).

**Comment by NiklasGollenstede** [comment]
Dammit. I just realized this this won't work. the "tabs" in the main UI are `about:blank` frames, so the above won't apply.
I've been meaning to change that, but for now the only way to change the style is by forking the extension.
The path to the theme style is specified in `re-style/views/index.js` line 5.

**Comment by NiklasGollenstede** [comment]
I just fixed that in the latest beta. Now my initial suggestion should work. The URL of the inner frames now mostly matches the one of the outer window.

**Comment by Madis0** [comment]
You could add an additional detection though, so that one could restyle reStyle without having to restart the browser repeatedly.

**Comment by Madis0** [comment]
So far I have done this:

<details><summary>White theme for reStyle</summary>

```css
/** ==UserStyle==
 * @name White theme for reStyle
 * @author Madis0
 * @license MIT
 * @description White theme for reStyle
 */

@-moz-document
  regexp("moz-extension://[\w-]+/reStyle(?!#panel).*")
{
	/* general */
	::selection {
		background-color: #f9f9fa;
		color: #0C0C0D;
		fill: #0C0C0D;
	}
	::-moz-selection {
		background-color: #f9f9fa;
		color: #0C0C0D;
		fill: #0C0C0D;
	} 
	html, body {
		background-color: #f9f9fa;
		color: #0C0C0D;
		fill: #0C0C0D;
	}
	::-webkit-scrollbar {
		background-color: #000;
	}
	::-webkit-scrollbar-thumb {
		background-color: #666;
	}

	/* inputs */
	textarea, input, select, .checkbox-wrapper>label {
		color: white;
		border-color: white;
		background-color: black;
	}
	textarea:focus, input:focus, select:focus, .checkbox-wrapper>input:focus ~ label {
		border-color: #7d7dff;
		box-shadow: 0 0 6px 0 #4444ff;
	}
	textarea:active:focus, input:active:focus, select:active:focus, .checkbox-wrapper>input:active:focus ~ label {
		border-color: #0000f0;
		box-shadow: 0 0 2px 1px blue;
	}
	textarea::selection, input::selection {
		background-color: #39f;
		color: white;
	}
	textarea::-moz-selection, input::-moz-selection {
		background-color: #39f;
		color: white;
	}
	.checkbox-wrapper>label::after {
		text-shadow: 0 0 5px green, 0 0 5px green, 0 0 5px green;
	}
	.checkbox-wrapper>input:not(:checked) ~ label::after {
		color: black;
		text-shadow: 0 0 5px red, 0 0 5px red, 0 0 5px red;
	}
	.checkbox-wrapper>input:not([disabled]) ~ label:hover,
	input[type="button"]:not([disabled]):hover,
	button:not([disabled]):hover {
		border-color: #7d7dff;
	}
	.checkbox-wrapper>input[disabled] ~ label,
	textarea[disabled], input[disabled], select[disabled] {
		color: hsl(  0,  0%,  65%);
		border-color: hsl(  0,  0%,  65%);
		background-color: hsl(  0,  0%,  10%);
		-webkit-user-select: none;
		user-select: none;
	}
	select:not(:hover), _:-moz-tree-row(hover) { /* firefox only */
		-moz-appearance: none;
		padding-right: 24px;
	}
	input[type="number"]:not(:hover) { /* firefox only */
		-moz-appearance: textfield;
	}

	/* context menu */
	.popup-menu, .submenu {
		background-color: black;
		border-color: white;
	}
	.menu-item:hover {
		background-color: white; 
	}

	/* invalid inputs */
	input.invalid, .invalid input,
	select.invalid, .invalid select,
	textarea.invalid, .invalid textarea {
		color: white;
		border-color: red;
		background-color: #210006;
		border-color: red;
		box-shadow: 0 0 15px 0 red;
	}

	/* special elements */
	code {
		background-color: #666;
		color: #ebf5ff;
		box-shadow: 0 0 1px 0px white inset;
	}
	a:link {
		color: #009705;
	}
	a:link:visited {
		color: #004386;
	}

}
```
</details>
<br>
Notably I can't find the proper elements for sidebar and inputs, or the ones I found just don't work.
